import { Profile } from "./interfaces/profile";
import { SkillType } from "./types/skillType";

export const profile: Profile = {
  id: "mary-vikko-miller",
  name: "Mary Vikko Miller",
  title: "Software Test Engineer",
  contact: {
    email: "maryvikkoiizuka@gmail.com",
    phone: "+64 27 524 8815",
    location: "Auckland, New Zealand",
    linkedin: "https://www.linkedin.com/in/mary-vikko-miller/",
  },
  summary:
    "Detail-oriented Test Engineer with 5+ years experience in Wealth Banking Systems, specialising in manual and automation testing. Strong background in Functional, UI, System, Regression, and Performance Testing across complex financial applications. Certified Avaloq Professional with hands-on experience collaborating closely with Developers, BAs, and Product Owners in Agile and Waterfall environments. Currently pursuing a Master of Information Technology at Auckland Institute of Studies and seeking an internship to contribute practical expertise to NZ-based projects.",
  experience: [
    {
      id: "experience-1",
      title: "Senior Consultant (Automation and Manual Tester)",
      company: "NTT Data Singapore Pte Ltd",
      clients: ["Development Bank of Singapore (DBS) - Digimarkets Team"],
      location: "Singapore",
      startDate: "July 2022",
      endDate: "August 2025",
      description: "",
      technologies: [],
      tasks: [
        "Performed Functional, UI, System, and Regression Testing within Agile sprints",
        "Designed and executed manual test cases for new features using Zephyr",
        "Built and maintained automated regression test scripts using Selenium with Java, reducing overall testing time",
        "Integrated automated tests into CI/CD pipelines with Jenkins for continuous validation",
        "Logged, tracked, and managed defects in Jira, producing sprint-level test reports",
        "Documented test plans, test cases, and results in Confluence",
        "Managed test code and collaboration using Bitbucket",
      ],
      current: false,
    },
    {
      id: "experience-2",
      title: "Test Engineer",
      company: "NTT Data Singapore Pte Ltd",
      clients: [
        "Development Bank of Singapore (DBS) - Avaloq & Digimarkets Team",
      ],
      location: "Singapore",
      startDate: "August 2017",
      endDate: "August 2019",
      description: "",
      technologies: [],
      tasks: [
        "Designed and executed manual test cases for new features using Zephyr",
        "Executed UI and functional testing to ensure system accuracy and stability",
        "Prepared and shared performance test summaries with stakeholders",
        "Logged, tracked, and prioritized defects in Jira and HP ALM",
        "Identified automation candidates and collaborated closely with Developers and Business Analysts",
        "Documented test cases, results, and processes in Confluence",
      ],
      current: false,
    },
    {
      id: "experience-3",
      title: "Software Engineer",
      company: "SOFGEN Holdings Ltd (Philippines)",
      clients: ["Amanah Raya Berhad - Avaloq Core Banking System"],
      location: "Philippines",
      startDate: "November 2014",
      endDate: "May 2017",
      description: "",
      technologies: [],
      tasks: [
        "Developed PL/SQL migration scripts and optimized database queries",
        "Analyzed requirements, enhancements, and bug tickets using Jira",
        "Designed report layouts and improved banking workflows",
        "Conducted unit and regression testing; created and maintained RTMs",
        "Performed data masking and supported system security configuration",
        "Enhanced GUI components and implemented new features",
        "Wrote functional specifications and executed unit tests, documenting in Confluence",
        "Migrated system changes across multiple client environments",
        "Resolved daily data consistency issues in Avaloq core banking system",
      ],
      current: false,
    },
  ],
  skills: [
    { id: "skill-1", name: "JIRA", type: SkillType.TECHNICAL },
    { id: "skill-2", name: "Zephyr", type: SkillType.TECHNICAL },
    { id: "skill-3", name: "Confluence", type: SkillType.TECHNICAL },
    { id: "skill-4", name: "IntelliJ", type: SkillType.TECHNICAL },
    { id: "skill-5", name: "Serenity BDD", type: SkillType.TECHNICAL },
    { id: "skill-6", name: "Selenium", type: SkillType.TECHNICAL },
    { id: "skill-7", name: "Java", type: SkillType.TECHNICAL },
    { id: "skill-8", name: "GIT", type: SkillType.TECHNICAL },
    { id: "skill-9", name: "Jenkins", type: SkillType.TECHNICAL },
    { id: "skill-10", name: "Postman", type: SkillType.TECHNICAL },
    { id: "skill-11", name: "Kafka", type: SkillType.TECHNICAL },
    { id: "skill-12", name: "HP ALM", type: SkillType.TECHNICAL },

    {
      id: "skill-13",
      name: "Manual & Automation Testing (Functional, UI, System, Regression, Performance)",
      type: SkillType.KEY,
    },
    {
      id: "skill-14",
      name: "Avaloq Banking Suite (Avaloq Certified Professional)",
      type: SkillType.KEY,
    },
    {
      id: "skill-15",
      name: "Test case design, execution, and optimisation",
      type: SkillType.KEY,
    },
    {
      id: "skill-16",
      name: "Defect lifecycle management",
      type: SkillType.KEY,
    },
    {
      id: "skill-17",
      name: "Agile Scrum & Waterfall methodologies",
      type: SkillType.KEY,
    },
  ],
  education: [
    {
      id: "education-1",
      institution: "Auckland Institute of Studies",
      degree: "Master of Information Technology",
      startDate: "September 2025",
      endDate: "Present",
      achievments: [],
      current: true,
    },
    {
      id: "education-2",
      institution: "Don Bosco College",
      degree: "Bachelor of Science in Information Technology",
      startDate: "June 2010",
      endDate: "April 2014",
      achievments: [
        "Best Capstone Project: “Little John’s Math Adventures” (Java/JavaME, Cocos2d)",
      ],
      current: false,
    },
  ],
};
